[dependency-groups]
dev = ["mypy>=1.17.0", "pytest>=8.4.1", "ruff>=0.12.4"]

[project]
authors = [{ email = "julian.lf.olate@gmail.com", name = "olatejulian" }]
dependencies = ["pygame>=2.6.1", "pytmx>=3.32"]
description = "Default template for PDM package"
license = { text = "MIT" }
name = "miko"
readme = "README.md"
requires-python = "==3.13.*"
version = "0.1.0"

[tool.pdm]
distribution = false
